# Generated by Django 4.1.7 on 2023-02-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceChats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('tg_link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'SourceChats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TargetChats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('tg_link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'TargetChats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WhiteList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'WhiteList',
                'managed': False,
            },
        ),
    ]
