# Generated by Django 4.1.7 on 2023-02-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botadminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MAIN_CONFIG', max_length=15, unique=True)),
                ('default_lang_code', models.CharField(default='ru', max_length=5)),
                ('used_languages', models.CharField(default='en, ru, pl, uk, de, it', max_length=500)),
                ('ask_open_ai', models.BooleanField(default=False)),
                ('abuser_on', models.BooleanField(default=False)),
                ('autotranslate', models.BooleanField(default=False)),
                ('autotranslate_lang', models.CharField(default='en', max_length=5)),
            ],
            options={
                'db_table': 'BotConfig',
            },
        ),
    ]
